 summary info ===============================================================================================================================
FAILED test.py::test_good_input - assert 1 == 0
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================================================================ 1 failed, 4 passed in 0.45s =============================================================================================================================
make: *** [Makefile:4: test] Error 1
~/.../assignments/09_blastomatic$ ^C
~/.../assignments/09_blastomatic$ chmod +x blastomatic.py
~/.../assignments/09_blastomatic$ make test
pytest -xv test.py blastomatic.py
========================================================== test session starts ==========================================================
platform linux -- Python 3.12.7, pytest-8.3.4, pluggy-1.5.0 -- /nix/store/nqlc7ymyglrsfx1hlssssq6zzy0hmk2c-python-wrapped-0.1.0/bin/python3
cachedir: .pytest_cache
rootdir: /home/runner/workspace/assignments/09_blastomatic
plugins: pylint-0.21.0, mypy-0.10.3, flake8-1.3.0
collected 8 items                                                                                                                       

test.py::test_exists PASSED                                                                                                       [ 12%]
test.py::test_usage FAILED                                                                                                        [ 25%]

=============================================================== FAILURES ================================================================
______________________________________________________________ test_usage _______________________________________________________________

    def test_usage() -> None:
        """ Usage """
    
        for flag in ['-h', '--help']:
            rv, out = getstatusoutput(f'{PRG} {flag}')
>           assert rv == 0
E           assert 2 == 0

test.py:30: AssertionError
======================================================== short test summary info ========================================================
FAILED test.py::test_usage - assert 2 == 0
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
====================================================== 1 failed, 1 passed in 0.07s ======================================================
make: *** [Makefile:4: test] Error 1
~/.../assignments/09_blastomatic$ 